### ISSUE TITLE
MIT/Apache License?

### ISSUE THREAD

**Issue by billylindeman** [StoicDeveloper/mapped_futures#6]
Hi @StoicDeveloper, I found this crate from your PR on futures-rs, but this crate is GPL whereas futures-rs is MIT/APACHE.  

I'm curious if you would be willing to re-release this crate under a more permissive license like futures-rs?

**Comment by billylindeman** [comment]
@StoicDeveloper bump

**Comment by StoicDeveloper** [comment]
Is there a particular change you want which cannot be released? If that PR ever makes progress then these features will obviously be available under the permissive license anyway.

**Comment by billylindeman** [comment]
I'm mainly requesting if this crate could be listed as MIT/Apache (ie putting that license in this repo / on cargo) it would be very helpful :) I figured since the core functionality is already available on the more permissive license via the futures-rs PR that you'd consider permitting this crate as MIT/Apache

**Comment by billylindeman** [comment]
@StoicDeveloper thoughts on the above?

**Comment by StoicDeveloper** [comment]
I prefer copyleft to permissive licenses. If the PR mentioned above ever gets merged, then of course the functionality will be under the same license as futures-rs, but I'm sorry, I don't see a reason to change the license until then. If your use-case requires edits to this module, you could always submit a PR, or fork the project, in order to be compliant with the license.

**Comment by billylindeman** [comment]
@StoicDeveloper as it stands today - it is not compliant to even *use* your crate via cargo in a project because rust statically links it.  Technically, that would be GPL violation.  

I could just use the branch published on futures-rs since that is already published with a more permissive license, but I figured since you are already pushing similar code with a permissive license elsewhere you'd consider adding that license here.   

If you're not open to it I understand, but just wanted to point out the implication that this is basically un-useable via cargo today

**Comment by StoicDeveloper** [comment]
Ah that is an excellent point, quite the oversight on my part. I will change the crate to a permissive license.

**Comment by billylindeman** [comment]
@StoicDeveloper hey just curious if you have a chance to tackle this?  I can make a PR if you're open to it.  I want to use it in a project but we are prohibited from shipping GPL, so it would be very helpful to have this changed officially in the repo / Cargo.toml 🙏

**Comment by StoicDeveloper** [comment]
apologies, this slipped my mind. Version 0.2 now has the MIT license.

**Comment by billylindeman** [comment]
🙏 thank you! much appreciated
